name: Deploy Serverless Api Gateway

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup DotNet Core Environment
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Install Lambda Tools
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CF_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CF_SECRET_ACCESS_KEY }}
          aws-region: 'ap-southeast-2'
      - name: Deploy Serverless
        run: |
          dotnet lambda deploy-serverless --template src/AWSServerlessAPI/deployment/app/templates/serverless.template --stackname AWSServerlessAPI-example --region ap-southeast-2 --s3-bucket ${{ secrets.S3_DEPLOY_BUCKET }}