name: Deploy Serverless Api Gateway

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create or Update Cloudformation
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '3.1.x'
      - name: Install Lambda Tools
        run: |
          dotnet tool install -g Amazon.Lambda.Tools
      - name: Deploy Serverless
        run: |
          dotnet lambda deploy-serverless --template serverless.template --stackname AWSServerlessAPI --region ap-southeast-2 --s3-bucket artifact-store-applications-ism0080